# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Andrew Gay's Portfolio
description: > # this means to ignore newlines until "baseurl:"
  This website contains a portfolio of Andrew Gay's 
  school work such as projects, notes, and completed courses.
baseurl: "" # the subpath of your site, e.g. /blog
#url: ""

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: compressed

# Gem settings
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jekyll-github-metadata

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - SITECHANGELOG.md
# End

# Github metadata settings
repository: nardwe/nardwe.github.io
# End

# jekyll-seo-tag settings
social:
  name: nardwe
  links:
    - https://teamtreehouse.com/andrewcarsongay
    - https://github.com/nardwe

logo: /assets/img/logo/logo.png

teamtreehouse:
  username: andrewcarsongay
#End

# Date format settings
date_format: "%b %-d, %Y"
# End

# Site permalink settings
permalink: /:title/
# End

# Collections settings
collections:
  documentation:
    output: true
    permalink: /:collection/:path
# End

# Site menu settings
menu:
  - title: "Blog"
    url: "/blog"
  - title: "Schools"
    url: "/schools"
  - title: "Awards"
    url: "/awards"
  - title: "About"
    url: "/acout"
# End

category_order:
  - 'Chemistry'
  - 'Spanish'
  - 'Programming'
  - 'Math'
  - 'Notes'
